AWSTemplateFormatVersion: "2010-09-09"
Description: Creates SSM parameters that set advanced options for the Amazon EKS Quick Start.
Parameters:
  ConfigSetName:
    Type: String
    Description: Name for the config set, the same name must be used when launching the main EKS Quick Start.
  EKSPrivateAccessEndpoint:
    Type: String
    AllowedValues: [Enabled, Disabled]
    Default: Enabled
  EKSClusterLoggingTypes:
    Type: String
    Default: ""
  EKSEncryptSecrets:
    Type: String
    AllowedValues: [Enabled, Disabled]
    Default: Enabled
  EKSEncryptSecretsKmsKeyArn:
    Type: String
    Default: ""
Mappings:
  Config:
    ParameterPrefix: { Value: '/quickstart/amazon-eks' }
Resources:
  EKSPrivateAccessEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Sub >
        {
          "Value": "${EKSPrivateAccessEndpoint}"
        }
      Name: !Sub ["${ParameterPrefix}/${ConfigSetName}/controlplane/EKSPrivateAccessEndpoint", {ParameterPrefix: !FindInMap [Config, ParameterPrefix, Value]}]
  EKSClusterLoggingTypesParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Sub >
        {
          "Value": "${EKSClusterLoggingTypes}"
        }
      Name: !Sub ["${ParameterPrefix}/${ConfigSetName}/controlplane/EKSClusterLoggingTypes", {ParameterPrefix: !FindInMap [Config, ParameterPrefix, Value]}]
  EKSEncryptSecretsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Sub >
        {
          "Value": "${EKSEncryptSecrets}"
        }
      Name: !Sub ["${ParameterPrefix}/${ConfigSetName}/controlplane/EKSEncryptSecrets", {ParameterPrefix: !FindInMap [Config, ParameterPrefix, Value]}]
  EKSEncryptSecretsKmsKeyArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Sub >
        {
          "Value": "${EKSEncryptSecretsKmsKeyArn}"
        }
      Name: !Sub ["${ParameterPrefix}/${ConfigSetName}/controlplane/EKSEncryptSecretsKmsKeyArn", {ParameterPrefix: !FindInMap [Config, ParameterPrefix, Value]}]
